// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMedicalRecords.proto

package DS_CA.SmartMedicalRecords;

public interface ConsultIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ConsultIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string coulID = 1;</code>
   */
  java.lang.String getCoulID();
  /**
   * <code>string coulID = 1;</code>
   */
  com.google.protobuf.ByteString
      getCoulIDBytes();
}
