// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMedicalRecords.proto

package DS_CA.SmartMedicalRecords;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Empty)
    com.google.protobuf.MessageOrBuilder {
}
