// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMedicalRecords.proto

package DS_CA.SmartMedicalRecords;

/**
 * Protobuf type {@code service1.MedicineListResponse}
 */
public  final class MedicineListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.MedicineListResponse)
    MedicineListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MedicineListResponse.newBuilder() to construct.
  private MedicineListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MedicineListResponse() {
    prescription_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MedicineListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            prescription_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DS_CA.SmartMedicalRecords.SmartMedicalRecordsImpl.internal_static_service1_MedicineListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DS_CA.SmartMedicalRecords.SmartMedicalRecordsImpl.internal_static_service1_MedicineListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DS_CA.SmartMedicalRecords.MedicineListResponse.class, DS_CA.SmartMedicalRecords.MedicineListResponse.Builder.class);
  }

  public static final int PRESCRIPTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object prescription_;
  /**
   * <code>string prescription = 1;</code>
   */
  public java.lang.String getPrescription() {
    java.lang.Object ref = prescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prescription_ = s;
      return s;
    }
  }
  /**
   * <code>string prescription = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPrescriptionBytes() {
    java.lang.Object ref = prescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPrescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, prescription_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPrescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, prescription_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DS_CA.SmartMedicalRecords.MedicineListResponse)) {
      return super.equals(obj);
    }
    DS_CA.SmartMedicalRecords.MedicineListResponse other = (DS_CA.SmartMedicalRecords.MedicineListResponse) obj;

    boolean result = true;
    result = result && getPrescription()
        .equals(other.getPrescription());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getPrescription().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DS_CA.SmartMedicalRecords.MedicineListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DS_CA.SmartMedicalRecords.MedicineListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service1.MedicineListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.MedicineListResponse)
      DS_CA.SmartMedicalRecords.MedicineListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DS_CA.SmartMedicalRecords.SmartMedicalRecordsImpl.internal_static_service1_MedicineListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DS_CA.SmartMedicalRecords.SmartMedicalRecordsImpl.internal_static_service1_MedicineListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DS_CA.SmartMedicalRecords.MedicineListResponse.class, DS_CA.SmartMedicalRecords.MedicineListResponse.Builder.class);
    }

    // Construct using DS_CA.SmartMedicalRecords.MedicineListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      prescription_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DS_CA.SmartMedicalRecords.SmartMedicalRecordsImpl.internal_static_service1_MedicineListResponse_descriptor;
    }

    @java.lang.Override
    public DS_CA.SmartMedicalRecords.MedicineListResponse getDefaultInstanceForType() {
      return DS_CA.SmartMedicalRecords.MedicineListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public DS_CA.SmartMedicalRecords.MedicineListResponse build() {
      DS_CA.SmartMedicalRecords.MedicineListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public DS_CA.SmartMedicalRecords.MedicineListResponse buildPartial() {
      DS_CA.SmartMedicalRecords.MedicineListResponse result = new DS_CA.SmartMedicalRecords.MedicineListResponse(this);
      result.prescription_ = prescription_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DS_CA.SmartMedicalRecords.MedicineListResponse) {
        return mergeFrom((DS_CA.SmartMedicalRecords.MedicineListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DS_CA.SmartMedicalRecords.MedicineListResponse other) {
      if (other == DS_CA.SmartMedicalRecords.MedicineListResponse.getDefaultInstance()) return this;
      if (!other.getPrescription().isEmpty()) {
        prescription_ = other.prescription_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DS_CA.SmartMedicalRecords.MedicineListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DS_CA.SmartMedicalRecords.MedicineListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object prescription_ = "";
    /**
     * <code>string prescription = 1;</code>
     */
    public java.lang.String getPrescription() {
      java.lang.Object ref = prescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prescription = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPrescriptionBytes() {
      java.lang.Object ref = prescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prescription = 1;</code>
     */
    public Builder setPrescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      prescription_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string prescription = 1;</code>
     */
    public Builder clearPrescription() {
      
      prescription_ = getDefaultInstance().getPrescription();
      onChanged();
      return this;
    }
    /**
     * <code>string prescription = 1;</code>
     */
    public Builder setPrescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      prescription_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.MedicineListResponse)
  }

  // @@protoc_insertion_point(class_scope:service1.MedicineListResponse)
  private static final DS_CA.SmartMedicalRecords.MedicineListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DS_CA.SmartMedicalRecords.MedicineListResponse();
  }

  public static DS_CA.SmartMedicalRecords.MedicineListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MedicineListResponse>
      PARSER = new com.google.protobuf.AbstractParser<MedicineListResponse>() {
    @java.lang.Override
    public MedicineListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MedicineListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MedicineListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MedicineListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public DS_CA.SmartMedicalRecords.MedicineListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

