// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMedicalRecords.proto

package DS_CA.SmartMedicalRecords;

public interface MedicineListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.MedicineListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string prescription = 1;</code>
   */
  java.lang.String getPrescription();
  /**
   * <code>string prescription = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrescriptionBytes();
}
