// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMedicalRecords.proto

package DS_CA.SmartMedicalRecords;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service1.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.service1.Message.Enum detail = 1;</code>
   */
  DS_CA.SmartMedicalRecords.Message.Enum getDetail();
}
