// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMedicalRecords.proto

package DS_CA.SmartMedicalRecords;

public interface PatientIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.PatientIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pID = 1;</code>
   */
  java.lang.String getPID();
  /**
   * <code>string pID = 1;</code>
   */
  com.google.protobuf.ByteString
      getPIDBytes();
}
