// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMedicalRecords.proto

package DS_CA.SmartMedicalRecords;

public interface PatientRecordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.PatientRecordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
