// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartMedicalRecords.proto

package DS_CA.SmartMedicalRecords;

public final class SmartMedicalRecordsImpl {
  private SmartMedicalRecordsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_PatientIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_PatientIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_PatientRecordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_PatientRecordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_ConsultIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_ConsultIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_MedicineListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_MedicineListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SmartMedicalRecords.proto\022\010service1\"\037\n" +
      "\020PatientIDRequest\022\013\n\003pID\030\001 \001(\t\"$\n\025Patien" +
      "tRecordResponse\022\013\n\003val\030\001 \001(\t\"Y\n\007Message\022" +
      "&\n\006detail\030\001 \001(\0162\026.service1.Message.Enum\"" +
      "&\n\004Enum\022\013\n\007UNKNOWN\020\000\022\007\n\003LOW\020\001\022\010\n\004HIGH\020\002\"" +
      "\007\n\005Empty\"\"\n\020ConsultIDRequest\022\016\n\006coulID\030\001" +
      " \001(\t\",\n\024MedicineListResponse\022\024\n\014prescrip" +
      "tion\030\001 \001(\t2\345\001\n\023SmartMedicalRecords\022M\n\014re" +
      "cordAccess\022\032.service1.PatientIDRequest\032\037" +
      ".service1.PatientRecordResponse\"\000\022-\n\005emp" +
      "ty\022\021.service1.Message\032\017.service1.Empty\"\000" +
      "\022P\n\016accessPharmacy\022\032.service1.ConsultIDR" +
      "equest\032\036.service1.MedicineListResponse\"\000" +
      "(\001B6\n\031DS_CA.SmartMedicalRecordsB\027SmartMe" +
      "dicalRecordsImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_PatientIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_PatientIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_PatientIDRequest_descriptor,
        new java.lang.String[] { "PID", });
    internal_static_service1_PatientRecordResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_PatientRecordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_PatientRecordResponse_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_service1_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_service1_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_service1_ConsultIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_ConsultIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_ConsultIDRequest_descriptor,
        new java.lang.String[] { "CoulID", });
    internal_static_service1_MedicineListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_MedicineListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_MedicineListResponse_descriptor,
        new java.lang.String[] { "Prescription", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
