// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.Empty)
    com.google.protobuf.MessageOrBuilder {
}
