// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public final class HealthMonitoringSensorsImpl {
  private HealthMonitoringSensorsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_VisitorEntryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_VisitorEntryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_PatientBMIRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_PatientBMIRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_BMIResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_BMIResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035HealthMonitoringSensors.proto\022\010service" +
      "3\"(\n\023VisitorEntryRequest\022\021\n\ttempRange\030\001 " +
      "\001(\001\"\036\n\014TempResponse\022\016\n\006access\030\001 \001(\t\"3\n\021P" +
      "atientBMIRequest\022\016\n\006height\030\001 \001(\001\022\016\n\006weig" +
      "ht\030\002 \001(\001\"&\n\021BMIResultResponse\022\021\n\tbmiStat" +
      "us\030\001 \001(\t\"P\n\007Message\022,\n\toperation\030\001 \001(\0162\031" +
      ".service3.Message.Bmistat\"\027\n\007Bmistat\022\014\n\010" +
      "BMILEVEL\020\000\"\007\n\005Empty2\325\001\n\027HealthMonitoring" +
      "Sensors\022H\n\013tempScanner\022\035.service3.Visito" +
      "rEntryRequest\032\026.service3.TempResponse\"\000(" +
      "\001\022A\n\003bmi\022\033.service3.PatientBMIRequest\032\033." +
      "service3.BMIResultResponse\"\000\022-\n\005empty\022\021." +
      "service3.Message\032\017.service3.Empty\"\000B>\n\035D" +
      "S_CA.HealthMonitoringSensorsB\033HealthMoni" +
      "toringSensorsImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_VisitorEntryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_VisitorEntryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_VisitorEntryRequest_descriptor,
        new java.lang.String[] { "TempRange", });
    internal_static_service3_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_TempResponse_descriptor,
        new java.lang.String[] { "Access", });
    internal_static_service3_PatientBMIRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_PatientBMIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_PatientBMIRequest_descriptor,
        new java.lang.String[] { "Height", "Weight", });
    internal_static_service3_BMIResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_BMIResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_BMIResultResponse_descriptor,
        new java.lang.String[] { "BmiStatus", });
    internal_static_service3_Message_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_Message_descriptor,
        new java.lang.String[] { "Operation", });
    internal_static_service3_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service3_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
