// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public final class HealthMonitoringSensorsImpl {
  private HealthMonitoringSensorsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_VisitorEntryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_VisitorEntryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_PatientBMIRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_PatientBMIRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_BMIResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_BMIResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035HealthMonitoringSensors.proto\022\010service" +
      "3\"(\n\023VisitorEntryRequest\022\021\n\ttempRange\030\001 " +
      "\001(\001\"\036\n\014TempResponse\022\016\n\006access\030\001 \001(\t\"\204\001\n\021" +
      "PatientBMIRequest\022\016\n\006height\030\001 \001(\001\022\016\n\006wei" +
      "ght\030\002 \001(\001\0226\n\toperation\030\003 \001(\0162#.service3." +
      "PatientBMIRequest.Bmistat\"\027\n\007Bmistat\022\014\n\010" +
      "BMILEVEL\020\000\"&\n\021BMIResultResponse\022\021\n\tbmiSt" +
      "atus\030\001 \001(\t2\252\001\n\027HealthMonitoringSensors\022H" +
      "\n\013tempScanner\022\035.service3.VisitorEntryReq" +
      "uest\032\026.service3.TempResponse\"\000(\001\022E\n\003bmi\022" +
      "\033.service3.PatientBMIRequest\032\033.service3." +
      "BMIResultResponse\"\000(\0010\001B>\n\035DS_CA.HealthM" +
      "onitoringSensorsB\033HealthMonitoringSensor" +
      "sImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_VisitorEntryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_VisitorEntryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_VisitorEntryRequest_descriptor,
        new java.lang.String[] { "TempRange", });
    internal_static_service3_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_TempResponse_descriptor,
        new java.lang.String[] { "Access", });
    internal_static_service3_PatientBMIRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_PatientBMIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_PatientBMIRequest_descriptor,
        new java.lang.String[] { "Height", "Weight", "Operation", });
    internal_static_service3_BMIResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_BMIResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_BMIResultResponse_descriptor,
        new java.lang.String[] { "BmiStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
