// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public final class HealthMonitoringSensorsImpl {
  private HealthMonitoringSensorsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_VisitorEntryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_VisitorEntryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_PatientBMIRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_PatientBMIRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_BMIResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_BMIResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035HealthMonitoringSensors.proto\022\010service" +
      "3\"(\n\023VisitorEntryRequest\022\021\n\ttempRange\030\001 " +
      "\001(\001\"\036\n\014TempResponse\022\016\n\006access\030\001 \001(\t\" \n\021P" +
      "atientBMIRequest\022\013\n\003bmi\030\001 \001(\001\"#\n\021BMIResu" +
      "ltResponse\022\016\n\006status\030\001 \001(\t2\250\001\n\027HealthMon" +
      "itoringSensors\022H\n\013tempScanner\022\035.service3" +
      ".VisitorEntryRequest\032\026.service3.TempResp" +
      "onse\"\000(\001\022C\n\003BMI\022\033.service3.PatientBMIReq" +
      "uest\032\033.service3.BMIResultResponse\"\000(\001B>\n" +
      "\035DS_CA.HealthMonitoringSensorsB\033HealthMo" +
      "nitoringSensorsImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_VisitorEntryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_VisitorEntryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_VisitorEntryRequest_descriptor,
        new java.lang.String[] { "TempRange", });
    internal_static_service3_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_TempResponse_descriptor,
        new java.lang.String[] { "Access", });
    internal_static_service3_PatientBMIRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_PatientBMIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_PatientBMIRequest_descriptor,
        new java.lang.String[] { "Bmi", });
    internal_static_service3_BMIResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_BMIResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_BMIResultResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
