// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

/**
 * <pre>
 * Enum is a complex datatype that may contain other variables
 * </pre>
 *
 * Protobuf type {@code service3.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    operation_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            operation_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DS_CA.HealthMonitoringSensors.Message.class, DS_CA.HealthMonitoringSensors.Message.Builder.class);
  }

  /**
   * Protobuf enum {@code service3.Message.Bmistat}
   */
  public enum Bmistat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BMILEVEL = 0;</code>
     */
    BMILEVEL(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BMILEVEL = 0;</code>
     */
    public static final int BMILEVEL_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Bmistat valueOf(int value) {
      return forNumber(value);
    }

    public static Bmistat forNumber(int value) {
      switch (value) {
        case 0: return BMILEVEL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Bmistat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Bmistat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Bmistat>() {
            public Bmistat findValueByNumber(int number) {
              return Bmistat.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DS_CA.HealthMonitoringSensors.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final Bmistat[] VALUES = values();

    public static Bmistat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Bmistat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:service3.Message.Bmistat)
  }

  public static final int OPERATION_FIELD_NUMBER = 1;
  private int operation_;
  /**
   * <code>.service3.Message.Bmistat operation = 1;</code>
   */
  public int getOperationValue() {
    return operation_;
  }
  /**
   * <code>.service3.Message.Bmistat operation = 1;</code>
   */
  public DS_CA.HealthMonitoringSensors.Message.Bmistat getOperation() {
    @SuppressWarnings("deprecation")
    DS_CA.HealthMonitoringSensors.Message.Bmistat result = DS_CA.HealthMonitoringSensors.Message.Bmistat.valueOf(operation_);
    return result == null ? DS_CA.HealthMonitoringSensors.Message.Bmistat.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (operation_ != DS_CA.HealthMonitoringSensors.Message.Bmistat.BMILEVEL.getNumber()) {
      output.writeEnum(1, operation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (operation_ != DS_CA.HealthMonitoringSensors.Message.Bmistat.BMILEVEL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, operation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DS_CA.HealthMonitoringSensors.Message)) {
      return super.equals(obj);
    }
    DS_CA.HealthMonitoringSensors.Message other = (DS_CA.HealthMonitoringSensors.Message) obj;

    boolean result = true;
    result = result && operation_ == other.operation_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + operation_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DS_CA.HealthMonitoringSensors.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DS_CA.HealthMonitoringSensors.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DS_CA.HealthMonitoringSensors.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Enum is a complex datatype that may contain other variables
   * </pre>
   *
   * Protobuf type {@code service3.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.Message)
      DS_CA.HealthMonitoringSensors.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DS_CA.HealthMonitoringSensors.Message.class, DS_CA.HealthMonitoringSensors.Message.Builder.class);
    }

    // Construct using DS_CA.HealthMonitoringSensors.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      operation_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_Message_descriptor;
    }

    @java.lang.Override
    public DS_CA.HealthMonitoringSensors.Message getDefaultInstanceForType() {
      return DS_CA.HealthMonitoringSensors.Message.getDefaultInstance();
    }

    @java.lang.Override
    public DS_CA.HealthMonitoringSensors.Message build() {
      DS_CA.HealthMonitoringSensors.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public DS_CA.HealthMonitoringSensors.Message buildPartial() {
      DS_CA.HealthMonitoringSensors.Message result = new DS_CA.HealthMonitoringSensors.Message(this);
      result.operation_ = operation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DS_CA.HealthMonitoringSensors.Message) {
        return mergeFrom((DS_CA.HealthMonitoringSensors.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DS_CA.HealthMonitoringSensors.Message other) {
      if (other == DS_CA.HealthMonitoringSensors.Message.getDefaultInstance()) return this;
      if (other.operation_ != 0) {
        setOperationValue(other.getOperationValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DS_CA.HealthMonitoringSensors.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DS_CA.HealthMonitoringSensors.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int operation_ = 0;
    /**
     * <code>.service3.Message.Bmistat operation = 1;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.service3.Message.Bmistat operation = 1;</code>
     */
    public Builder setOperationValue(int value) {
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.service3.Message.Bmistat operation = 1;</code>
     */
    public DS_CA.HealthMonitoringSensors.Message.Bmistat getOperation() {
      @SuppressWarnings("deprecation")
      DS_CA.HealthMonitoringSensors.Message.Bmistat result = DS_CA.HealthMonitoringSensors.Message.Bmistat.valueOf(operation_);
      return result == null ? DS_CA.HealthMonitoringSensors.Message.Bmistat.UNRECOGNIZED : result;
    }
    /**
     * <code>.service3.Message.Bmistat operation = 1;</code>
     */
    public Builder setOperation(DS_CA.HealthMonitoringSensors.Message.Bmistat value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.service3.Message.Bmistat operation = 1;</code>
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.Message)
  }

  // @@protoc_insertion_point(class_scope:service3.Message)
  private static final DS_CA.HealthMonitoringSensors.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DS_CA.HealthMonitoringSensors.Message();
  }

  public static DS_CA.HealthMonitoringSensors.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public DS_CA.HealthMonitoringSensors.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

