// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service3.Message.Bmistat operation = 1;</code>
   */
  int getOperationValue();
  /**
   * <code>.service3.Message.Bmistat operation = 1;</code>
   */
  DS_CA.HealthMonitoringSensors.Message.Bmistat getOperation();
}
