// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public interface PatientBMIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.PatientBMIRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double bmi = 1;</code>
   */
  double getBmi();
}
