// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public interface PatientBMIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.PatientBMIRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double height = 1;</code>
   */
  double getHeight();

  /**
   * <code>double weight = 2;</code>
   */
  double getWeight();

  /**
   * <code>.service3.PatientBMIRequest.Bmistat operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.service3.PatientBMIRequest.Bmistat operation = 3;</code>
   */
  DS_CA.HealthMonitoringSensors.PatientBMIRequest.Bmistat getOperation();
}
