// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access = 1;</code>
   */
  java.lang.String getAccess();
  /**
   * <code>string access = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessBytes();
}
