// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

public interface VisitorEntryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.VisitorEntryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double tempRange = 1;</code>
   */
  double getTempRange();
}
