// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringSensors.proto

package DS_CA.HealthMonitoringSensors;

/**
 * <pre>
 * define each variable in rpc method separately
 * for client streaming variables
 * </pre>
 *
 * Protobuf type {@code service3.VisitorEntryRequest}
 */
public  final class VisitorEntryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.VisitorEntryRequest)
    VisitorEntryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VisitorEntryRequest.newBuilder() to construct.
  private VisitorEntryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VisitorEntryRequest() {
    tempRange_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VisitorEntryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            tempRange_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_VisitorEntryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_VisitorEntryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DS_CA.HealthMonitoringSensors.VisitorEntryRequest.class, DS_CA.HealthMonitoringSensors.VisitorEntryRequest.Builder.class);
  }

  public static final int TEMPRANGE_FIELD_NUMBER = 1;
  private double tempRange_;
  /**
   * <code>double tempRange = 1;</code>
   */
  public double getTempRange() {
    return tempRange_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tempRange_ != 0D) {
      output.writeDouble(1, tempRange_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tempRange_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, tempRange_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DS_CA.HealthMonitoringSensors.VisitorEntryRequest)) {
      return super.equals(obj);
    }
    DS_CA.HealthMonitoringSensors.VisitorEntryRequest other = (DS_CA.HealthMonitoringSensors.VisitorEntryRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getTempRange())
        == java.lang.Double.doubleToLongBits(
            other.getTempRange()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPRANGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTempRange()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DS_CA.HealthMonitoringSensors.VisitorEntryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * define each variable in rpc method separately
   * for client streaming variables
   * </pre>
   *
   * Protobuf type {@code service3.VisitorEntryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.VisitorEntryRequest)
      DS_CA.HealthMonitoringSensors.VisitorEntryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_VisitorEntryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_VisitorEntryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DS_CA.HealthMonitoringSensors.VisitorEntryRequest.class, DS_CA.HealthMonitoringSensors.VisitorEntryRequest.Builder.class);
    }

    // Construct using DS_CA.HealthMonitoringSensors.VisitorEntryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tempRange_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DS_CA.HealthMonitoringSensors.HealthMonitoringSensorsImpl.internal_static_service3_VisitorEntryRequest_descriptor;
    }

    @java.lang.Override
    public DS_CA.HealthMonitoringSensors.VisitorEntryRequest getDefaultInstanceForType() {
      return DS_CA.HealthMonitoringSensors.VisitorEntryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public DS_CA.HealthMonitoringSensors.VisitorEntryRequest build() {
      DS_CA.HealthMonitoringSensors.VisitorEntryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public DS_CA.HealthMonitoringSensors.VisitorEntryRequest buildPartial() {
      DS_CA.HealthMonitoringSensors.VisitorEntryRequest result = new DS_CA.HealthMonitoringSensors.VisitorEntryRequest(this);
      result.tempRange_ = tempRange_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DS_CA.HealthMonitoringSensors.VisitorEntryRequest) {
        return mergeFrom((DS_CA.HealthMonitoringSensors.VisitorEntryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DS_CA.HealthMonitoringSensors.VisitorEntryRequest other) {
      if (other == DS_CA.HealthMonitoringSensors.VisitorEntryRequest.getDefaultInstance()) return this;
      if (other.getTempRange() != 0D) {
        setTempRange(other.getTempRange());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DS_CA.HealthMonitoringSensors.VisitorEntryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DS_CA.HealthMonitoringSensors.VisitorEntryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double tempRange_ ;
    /**
     * <code>double tempRange = 1;</code>
     */
    public double getTempRange() {
      return tempRange_;
    }
    /**
     * <code>double tempRange = 1;</code>
     */
    public Builder setTempRange(double value) {
      
      tempRange_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double tempRange = 1;</code>
     */
    public Builder clearTempRange() {
      
      tempRange_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.VisitorEntryRequest)
  }

  // @@protoc_insertion_point(class_scope:service3.VisitorEntryRequest)
  private static final DS_CA.HealthMonitoringSensors.VisitorEntryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DS_CA.HealthMonitoringSensors.VisitorEntryRequest();
  }

  public static DS_CA.HealthMonitoringSensors.VisitorEntryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VisitorEntryRequest>
      PARSER = new com.google.protobuf.AbstractParser<VisitorEntryRequest>() {
    @java.lang.Override
    public VisitorEntryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VisitorEntryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VisitorEntryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VisitorEntryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public DS_CA.HealthMonitoringSensors.VisitorEntryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

