// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMotionSensors.proto

package DS_CA.PatientMotionSensors;

public interface DoctorEntryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.DoctorEntryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
