// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMotionSensors.proto

package DS_CA.PatientMotionSensors;

public interface MonitorAlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.MonitorAlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alert = 1;</code>
   */
  java.lang.String getAlert();
  /**
   * <code>string alert = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertBytes();
}
