// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMotionSensors.proto

package DS_CA.PatientMotionSensors;

public interface PatientCabinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.PatientCabinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool action = 1;</code>
   */
  boolean getAction();
}
