// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMotionSensors.proto

package DS_CA.PatientMotionSensors;

/**
 * <pre>
 * define each variable in rpc method separately
 * </pre>
 *
 * Protobuf type {@code service2.PatientCabinRequest}
 */
public  final class PatientCabinRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service2.PatientCabinRequest)
    PatientCabinRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PatientCabinRequest.newBuilder() to construct.
  private PatientCabinRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PatientCabinRequest() {
    action_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PatientCabinRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            action_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DS_CA.PatientMotionSensors.PatientMotionSensorsImpl.internal_static_service2_PatientCabinRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DS_CA.PatientMotionSensors.PatientMotionSensorsImpl.internal_static_service2_PatientCabinRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DS_CA.PatientMotionSensors.PatientCabinRequest.class, DS_CA.PatientMotionSensors.PatientCabinRequest.Builder.class);
  }

  public static final int ACTION_FIELD_NUMBER = 1;
  private boolean action_;
  /**
   * <code>bool action = 1;</code>
   */
  public boolean getAction() {
    return action_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (action_ != false) {
      output.writeBool(1, action_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (action_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, action_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DS_CA.PatientMotionSensors.PatientCabinRequest)) {
      return super.equals(obj);
    }
    DS_CA.PatientMotionSensors.PatientCabinRequest other = (DS_CA.PatientMotionSensors.PatientCabinRequest) obj;

    boolean result = true;
    result = result && (getAction()
        == other.getAction());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAction());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DS_CA.PatientMotionSensors.PatientCabinRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DS_CA.PatientMotionSensors.PatientCabinRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * define each variable in rpc method separately
   * </pre>
   *
   * Protobuf type {@code service2.PatientCabinRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service2.PatientCabinRequest)
      DS_CA.PatientMotionSensors.PatientCabinRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DS_CA.PatientMotionSensors.PatientMotionSensorsImpl.internal_static_service2_PatientCabinRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DS_CA.PatientMotionSensors.PatientMotionSensorsImpl.internal_static_service2_PatientCabinRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DS_CA.PatientMotionSensors.PatientCabinRequest.class, DS_CA.PatientMotionSensors.PatientCabinRequest.Builder.class);
    }

    // Construct using DS_CA.PatientMotionSensors.PatientCabinRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      action_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DS_CA.PatientMotionSensors.PatientMotionSensorsImpl.internal_static_service2_PatientCabinRequest_descriptor;
    }

    @java.lang.Override
    public DS_CA.PatientMotionSensors.PatientCabinRequest getDefaultInstanceForType() {
      return DS_CA.PatientMotionSensors.PatientCabinRequest.getDefaultInstance();
    }

    @java.lang.Override
    public DS_CA.PatientMotionSensors.PatientCabinRequest build() {
      DS_CA.PatientMotionSensors.PatientCabinRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public DS_CA.PatientMotionSensors.PatientCabinRequest buildPartial() {
      DS_CA.PatientMotionSensors.PatientCabinRequest result = new DS_CA.PatientMotionSensors.PatientCabinRequest(this);
      result.action_ = action_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DS_CA.PatientMotionSensors.PatientCabinRequest) {
        return mergeFrom((DS_CA.PatientMotionSensors.PatientCabinRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DS_CA.PatientMotionSensors.PatientCabinRequest other) {
      if (other == DS_CA.PatientMotionSensors.PatientCabinRequest.getDefaultInstance()) return this;
      if (other.getAction() != false) {
        setAction(other.getAction());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DS_CA.PatientMotionSensors.PatientCabinRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DS_CA.PatientMotionSensors.PatientCabinRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean action_ ;
    /**
     * <code>bool action = 1;</code>
     */
    public boolean getAction() {
      return action_;
    }
    /**
     * <code>bool action = 1;</code>
     */
    public Builder setAction(boolean value) {
      
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool action = 1;</code>
     */
    public Builder clearAction() {
      
      action_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service2.PatientCabinRequest)
  }

  // @@protoc_insertion_point(class_scope:service2.PatientCabinRequest)
  private static final DS_CA.PatientMotionSensors.PatientCabinRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DS_CA.PatientMotionSensors.PatientCabinRequest();
  }

  public static DS_CA.PatientMotionSensors.PatientCabinRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PatientCabinRequest>
      PARSER = new com.google.protobuf.AbstractParser<PatientCabinRequest>() {
    @java.lang.Override
    public PatientCabinRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PatientCabinRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PatientCabinRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PatientCabinRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public DS_CA.PatientMotionSensors.PatientCabinRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

