// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientMotionSensors.proto

package DS_CA.PatientMotionSensors;

public interface ScheduledResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ScheduledResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string booking = 2;</code>
   */
  java.lang.String getBooking();
  /**
   * <code>string booking = 2;</code>
   */
  com.google.protobuf.ByteString
      getBookingBytes();
}
